# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/atakan/Desktop/github/FDR_Microrobot_Manipulation/FDR_Control2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1186, 883)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Desktop/Despacho_U_M_V0.1/Imagens/dump-truck.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_12.setGeometry(QtCore.QRect(170, 90, 341, 301))
        self.formLayoutWidget_12.setObjectName("formLayoutWidget_12")
        self.formLayout_23 = QtWidgets.QFormLayout(self.formLayoutWidget_12)
        self.formLayout_23.setContentsMargins(0, 0, 0, 0)
        self.formLayout_23.setObjectName("formLayout_23")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_23.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_23.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_23.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(8)
        self.label_2.setObjectName("label_2")
        self.formLayout_23.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.formLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_13.setGeometry(QtCore.QRect(170, 410, 339, 161))
        self.formLayoutWidget_13.setObjectName("formLayoutWidget_13")
        self.formLayout_24 = QtWidgets.QFormLayout(self.formLayoutWidget_13)
        self.formLayout_24.setContentsMargins(0, 0, 0, 0)
        self.formLayout_24.setObjectName("formLayout_24")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setLineWidth(8)
        self.label_6.setObjectName("label_6")
        self.formLayout_24.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_24.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_24.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.formLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_14.setGeometry(QtCore.QRect(170, 590, 339, 161))
        self.formLayoutWidget_14.setObjectName("formLayoutWidget_14")
        self.formLayout_25 = QtWidgets.QFormLayout(self.formLayoutWidget_14)
        self.formLayout_25.setContentsMargins(0, 0, 0, 0)
        self.formLayout_25.setObjectName("formLayout_25")
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.label_25.setFont(font)
        self.label_25.setLineWidth(8)
        self.label_25.setObjectName("label_25")
        self.formLayout_25.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_25)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_25.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_25.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 10, 511, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(15)
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(170, 570, 921, 20))
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(170, 390, 921, 20))
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(510, 590, 581, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Stop.setFont(font)
        self.Stop.setObjectName("Stop")
        self.Initial = QtWidgets.QPushButton(self.centralwidget)
        self.Initial.setGeometry(QtCore.QRect(510, 680, 581, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Initial.setFont(font)
        self.Initial.setObjectName("Initial")
        self.Current = QtWidgets.QPushButton(self.centralwidget)
        self.Current.setGeometry(QtCore.QRect(510, 504, 581, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Current.setFont(font)
        self.Current.setObjectName("Current")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(520, 340, 148, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.label_14.setFont(font)
        self.label_14.setLineWidth(11)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(510, 260, 581, 20))
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(520, 290, 91, 59))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Angle1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Angle1.setGeometry(QtCore.QRect(630, 300, 131, 51))
        self.Angle1.setObjectName("Angle1")
        self.Angle2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Angle2.setGeometry(QtCore.QRect(880, 300, 151, 51))
        self.Angle2.setObjectName("Angle2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(780, 290, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(170, 70, 921, 20))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setLineWidth(5)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(170, 760, 921, 20))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setLineWidth(5)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(510, 670, 581, 20))
        self.line_9.setLineWidth(5)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(780, 100, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.Lin2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Lin2.setGeometry(QtCore.QRect(890, 100, 151, 51))
        self.Lin2.setObjectName("Lin2")
        self.Lin1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Lin1.setGeometry(QtCore.QRect(630, 100, 131, 51))
        self.Lin1.setObjectName("Lin1")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(520, 100, 101, 59))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.Linear = QtWidgets.QPushButton(self.centralwidget)
        self.Linear.setGeometry(QtCore.QRect(510, 170, 581, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Linear.setFont(font)
        self.Linear.setObjectName("Linear")
        self.current_val = QtWidgets.QLineEdit(self.centralwidget)
        self.current_val.setGeometry(QtCore.QRect(720, 430, 131, 51))
        self.current_val.setObjectName("current_val")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(540, 420, 101, 59))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Control_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Control_2.setGeometry(QtCore.QRect(790, 10, 131, 51))
        self.Control_2.setObjectName("Control_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(630, 10, 141, 59))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1186, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ROS + PyQT GUI Example"))
        self.label_2.setText(_translate("MainWindow", "Manipulation"))
        self.label_6.setText(_translate("MainWindow", "Operation Mode"))
        self.label_25.setText(_translate("MainWindow", "Debugging Mode"))
        self.label_4.setText(_translate("MainWindow", "FDR MANIPULATION"))
        self.Stop.setText(_translate("MainWindow", "System Stop"))
        self.Initial.setText(_translate("MainWindow", "Send System To Initial"))
        self.Current.setText(_translate("MainWindow", "Activate Current"))
        self.label_7.setText(_translate("MainWindow", "Angle 1"))
        self.Angle1.setText(_translate("MainWindow", "0"))
        self.Angle2.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Angle 2"))
        self.label_10.setText(_translate("MainWindow", "Linear 2"))
        self.Lin2.setText(_translate("MainWindow", "0"))
        self.Lin1.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Linear 1"))
        self.Linear.setText(_translate("MainWindow", "Activate Linear Mechanism"))
        self.current_val.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Current"))
        self.Control_2.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "Controller"))

